/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author WEJE
 */
public class Student_portal extends javax.swing.JFrame {

    /**
     * Creates new form Student_portal
     */
    String getmat;
Connection conn = null;
ResultSet rs = null;
PreparedStatement pst = null;
String fullname;

    public Student_portal() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public Student_portal(String matno) {
        initComponents();
        setLocationRelativeTo(null);
        getmat = matno;
    }
    public void loadsupervisor_tbl()
    {
    try
{
conn = DriverManager.getConnection("jdbc:mysql://localhost/ssmdb", "root","root");   
String sql = "SELECT * FROM supervisor_tbl ";
pst= conn.prepareStatement(sql);
rs= pst.executeQuery();
supervisor_tbl.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e);
}
    }
    
    public void GetStudentDetails()
    {
              try
        {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ssmdb", "root","root");                 
    Statement st = (Statement) con.createStatement();
    ResultSet res = st.executeQuery("SELECT * FROM student_tbl WHERE mat_no ='"+getmat+"'");
        if(res.next())
        {
        String getfname = res.getString("firstname");
        String getlname = res.getString("lastname");
        fullname = getfname+" "+getlname;
        student_name.setText(fullname);
        }
        
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, e);
        } 
    }
    
    public void GetMatchedSupervisor()
    {
     try
{
  
         Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ssmdb", "root","root");                 
         Statement st = (Statement) con.createStatement();
         ResultSet res = st.executeQuery("SELECT * FROM matchresult_tbl WHERE Student ='"+fullname+"'"); 
        
         if(res.next())
         {

         String student_supervisor = res.getString("Supervisor");

         //setting text
         matchmsg.setText("Dear,"+fullname+" The Supervisor Assigned to you is "+student_supervisor);

         
         }    
}
    
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e);
}
    
    }
    
public void loadform()
{
loadsupervisor_tbl();
GetStudentDetails();
GetMatchedSupervisor();
}
public void UpdateStudentInfoWithPrefs()
{
try
{
conn = DriverManager.getConnection("jdbc:mysql://localhost/ssmdb", "root","root");      
String sql ="update student_tbl set interest1='"+ui1.getSelectedItem().toString()+"',interest2='"+ui2.getSelectedItem().toString()+"',interest3='"+ui3.getSelectedItem().toString()+"',interest4='"+ui4.getSelectedItem().toString()+"',interest5='"+ui5.getSelectedItem().toString()+"' where mat_no ='"+getmat+"'";
pst= conn.prepareStatement(sql);
pst.execute();
}

catch(Exception e)
{
JOptionPane.showMessageDialog(null, e);
}
}

public void SendtoStudentPrefList()
{
try
{
    
        String std_ID = getmat;
        String std_name = fullname;
        String interest1 = ui1.getSelectedItem().toString();
        String interest2 = ui2.getSelectedItem().toString();
        String interest3 = ui3.getSelectedItem().toString();
        String interest4 = ui4.getSelectedItem().toString();
        String interest5 = ui5.getSelectedItem().toString();
        
        
        conn = DriverManager.getConnection("jdbc:mysql://localhost/ssmdb", "root","root");
        Statement st = (Statement) conn.createStatement();
        String insert = "INSERT INTO matching_tbl VALUES ('" +std_ID+ "', '" +std_name+ "', '" +interest1+ "', '" +interest2+ "', '" +interest3+ "', '" +interest4+ "', '" +interest5+ "')";
        st.executeUpdate(insert);
        JOptionPane.showMessageDialog(null,"Successfully submitted Request to Project coodinator!");
  
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e);
}
    
}
public void updateStudentRecord()
{
SendtoStudentPrefList();
UpdateStudentInfoWithPrefs();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matchmsg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        student_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        supervisor_tbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ui1 = new javax.swing.JComboBox();
        ui2 = new javax.swing.JComboBox();
        ui3 = new javax.swing.JComboBox();
        ui4 = new javax.swing.JComboBox();
        ui5 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        i1 = new javax.swing.JTextField();
        i2 = new javax.swing.JTextField();
        i3 = new javax.swing.JTextField();
        i4 = new javax.swing.JTextField();
        i5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        s_name = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Portal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Student Portal");

        matchmsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(matchmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(matchmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Name:");

        student_name.setForeground(new java.awt.Color(255, 255, 255));

        supervisor_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        supervisor_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supervisor_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(supervisor_tbl);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("List of Available Supervisors");

        jLabel5.setText("Your Chosen Preference");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel6.setText("Supervisor One:");

        ui1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ui1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Marion Adebiyi", "Osamor Victor", "Jonathan Oluranti", "Charles Ayo", "Wole Francis" }));
        ui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui1ActionPerformed(evt);
            }
        });

        ui2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ui2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Marion Adebiyi", "Osamor Victor", "Jonathan Oluranti", "Charles Ayo", "Wole Francis" }));
        ui2.setEnabled(false);
        ui2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui2ActionPerformed(evt);
            }
        });

        ui3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ui3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Marion Adebiyi", "Osamor Victor", "Jonathan Oluranti", "Charles Ayo", "Wole Francis" }));
        ui3.setEnabled(false);
        ui3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui3ActionPerformed(evt);
            }
        });

        ui4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ui4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Marion Adebiyi", "Osamor Victor", "Jonathan Oluranti", "Charles Ayo", "Wole Francis" }));
        ui4.setEnabled(false);
        ui4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui4ActionPerformed(evt);
            }
        });

        ui5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ui5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Marion Adebiyi", "Osamor Victor", "Jonathan Oluranti", "Charles Ayo", "Wole Francis" }));
        ui5.setEnabled(false);
        ui5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setText("Supervisor Five:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setText("Supervisor Four:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Supervisor three:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setText("Supervisor Two:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setText("Selected Supervisor Preference");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel12.setText("Student One:");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel13.setText("Student Two:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setText("Student Three:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel15.setText("Student Four:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setText("Student Five:");

        i1.setEditable(false);
        i1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        i2.setEditable(false);
        i2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        i3.setEditable(false);
        i3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        i4.setEditable(false);
        i4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        i5.setEditable(false);
        i5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel17.setText("Supervisor Name:");

        s_name.setEditable(false);
        s_name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Submit Request");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Reset Preference List");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ui4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(ui3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ui1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ui2, 0, 249, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ui5, 0, 249, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(i4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s_name, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(student_name, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(266, 266, 266)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(student_name))
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ui2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ui3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ui4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ui5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(i1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(s_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(i2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(i3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(i4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadform();
    }//GEN-LAST:event_formWindowOpened

    private void supervisor_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supervisor_tblMouseClicked
        // TODO add your handling code here:
          try
        {
        int row = supervisor_tbl.getSelectedRow();
        String interest1=(supervisor_tbl.getModel().getValueAt(row, 5).toString());
        String interest2=(supervisor_tbl.getModel().getValueAt(row, 6).toString());
        String interest3=(supervisor_tbl.getModel().getValueAt(row, 7).toString());
        String interest4=(supervisor_tbl.getModel().getValueAt(row, 8).toString());
        String interest5=(supervisor_tbl.getModel().getValueAt(row, 9).toString());
        
        String getfname=(supervisor_tbl.getModel().getValueAt(row, 1).toString());
        String getlname=(supervisor_tbl.getModel().getValueAt(row, 2).toString());
        
       String fullname = getfname+" "+getlname;
        
        i1.setText(interest1);
        i2.setText(interest2);
        i3.setText(interest3);
        i4.setText(interest4);
        i5.setText(interest5);
        
        s_name.setText(fullname);
}
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null, e);
        }   
    }//GEN-LAST:event_supervisor_tblMouseClicked

    private void ui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui1ActionPerformed
        // TODO add your handling code here:
        String temp = ui1.getSelectedItem().toString();
        if(temp.equals("--Select--"))
        {
        JOptionPane.showMessageDialog(null,"Please select a valid interest");
         }
        
        else
        {
         ui2.setEnabled(true);
        ui2.removeItem(ui1.getSelectedItem().toString());
        }
       
    }//GEN-LAST:event_ui1ActionPerformed

    private void ui2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui2ActionPerformed
        // TODO add your handling code here:
          String temp = ui2.getSelectedItem().toString();
        if(temp.equals("--Select--"))
        {
        JOptionPane.showMessageDialog(null,"Please select a valid interest");
         }
        
        else
        {
        ui3.setEnabled(true);
        ui3.removeItem(ui1.getSelectedItem().toString());
        ui3.removeItem(ui2.getSelectedItem().toString());
    }
    }//GEN-LAST:event_ui2ActionPerformed

    private void ui3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui3ActionPerformed
        // TODO add your handling code here:
          String temp = ui3.getSelectedItem().toString();
        if(temp.equals("--Select--"))
        {
        JOptionPane.showMessageDialog(null,"Please select a valid interest");
         }
        
        else
        {
        ui4.setEnabled(true);
        ui4.removeItem(ui1.getSelectedItem().toString());
        ui4.removeItem(ui2.getSelectedItem().toString());
        ui4.removeItem(ui3.getSelectedItem().toString());
    }
    }//GEN-LAST:event_ui3ActionPerformed

    private void ui4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui4ActionPerformed
        // TODO add your handling code here:
          String temp = ui4.getSelectedItem().toString();
        if(temp.equals("--Select--"))
        {
        JOptionPane.showMessageDialog(null,"Please select a valid interest");
         }
        
        else
        {
        ui5.setEnabled(true);
        ui5.removeItem(ui1.getSelectedItem().toString());
        ui5.removeItem(ui2.getSelectedItem().toString());
        ui5.removeItem(ui3.getSelectedItem().toString());
        ui5.removeItem(ui4.getSelectedItem().toString());
    }
    }//GEN-LAST:event_ui4ActionPerformed

    private void ui5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui5ActionPerformed
        // TODO add your handling code here:
           String temp = ui5.getSelectedItem().toString();
        if(temp.equals("--Select--"))
        {
        JOptionPane.showMessageDialog(null,"Please select a valid interest");
         }
      
        
    }//GEN-LAST:event_ui5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateStudentRecord();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_portal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_portal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField i1;
    private javax.swing.JTextField i2;
    private javax.swing.JTextField i3;
    private javax.swing.JTextField i4;
    private javax.swing.JTextField i5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel matchmsg;
    private javax.swing.JTextField s_name;
    private javax.swing.JLabel student_name;
    private javax.swing.JTable supervisor_tbl;
    private javax.swing.JComboBox ui1;
    private javax.swing.JComboBox ui2;
    private javax.swing.JComboBox ui3;
    private javax.swing.JComboBox ui4;
    private javax.swing.JComboBox ui5;
    // End of variables declaration//GEN-END:variables
}
